# ==== I AGREE ====


# Offense count: 1
Style/MultilineTernaryOperator:
  Enabled: true

# Offense count: 1
# Cop supports --auto-correct.
Style/DefWithParentheses:
  Enabled: true

# Offense count: 1
# Cop supports --auto-correct.
Style/MethodCallParentheses:
  Enabled: true


# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyleInsidePipes, SupportedStyles.
Style/SpaceAroundBlockParameters:
  Enabled: true



# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyleForMultiline, SupportedStyles.
Style/TrailingComma:
  Enabled: true


# Offense count: 3
# Cop supports --auto-correct.
Style/SingleSpaceBeforeFirstArg:
  Enabled: true


# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/FirstParameterIndentation:
  Enabled: true

# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: AllowSafeAssignment.
Style/ParenthesesAroundCondition:
  Enabled: true


# Offense count: 2
# Cop supports --auto-correct.
Style/SpecialGlobalVars:
  Enabled: true


# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: IgnoredMethods.
Style/SymbolProc:
  Enabled: true



# Offense count: 4
# Cop supports --auto-correct.
Style/Lambda:
  Enabled: true


# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/MethodDefParentheses:
  Enabled: true


# Offense count: 3
# Cop supports --auto-correct.
Style/EmptyLiteral:
  Enabled: true

# Offense count: 3
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, UseHashRocketsWithSymbolValues.
Style/HashSyntax:
  Enabled: true


# Offense count: 3
# Cop supports --auto-correct.
Style/Not:
  Enabled: true





# Offense count: 5
# Cop supports --auto-correct.
# Configuration parameters: AllowMultipleReturnValues.
Style/RedundantReturn:
  Enabled: true


# Offense count: 17
# Cop supports --auto-correct.
Style/SpaceAfterComma:
  Enabled: true


# Offense count: 12
# Cop supports --auto-correct.
Style/SpaceAfterNot:
  Enabled: true


# Offense count: 49
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SignalException:
  Enabled: true


# Offense count: 21
# Cop supports --auto-correct.
Style/LineEndConcatenation:
  Enabled: true


# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/AndOr:
  Enabled: true

# Offense count: 11
# Cop supports --auto-correct.
# Configuration parameters: PreferredDelimiters.
Style/PercentLiteralDelimiters:
  Enabled: true


# Offense count: 47
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/MultilineOperationIndentation:
  Enabled: true


# Offense count: 35
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, AutoCorrectEncodingComment.
Style/Encoding:
  Enabled: true


# Offense count: 7
# Cop supports --auto-correct.
Lint/UnusedMethodArgument:
  Enabled: true

# Offense count: 1
# Cop supports --auto-correct.
Style/AlignArray:
  Enabled: true


# Offense count: 4
# Cop supports --auto-correct.
Style/ColonMethodCall:
  Enabled: true

# Offense count: 2
# Cop supports --auto-correct.
Lint/UnusedBlockArgument:
  Enabled: true

# Offense count: 19
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/DotPosition:
  Enabled: true


# Offense count: 8
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyElse:
  Enabled: true

# Offense count: 18
# Cop supports --auto-correct.
# Configuration parameters: MultiSpaceAllowedForOperators.
Style/SpaceAroundOperators:
  Enabled: true

# Offense count: 33
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SpaceBeforeBlockBraces:
  Enabled: true

# Offense count: 14
# Cop supports --auto-correct.
Style/SpaceBeforeComma:
  Enabled: true


# Offense count: 14
# Cop supports --auto-correct.
Style/SpaceInsideParens:
  Enabled: true



# Offense count: 18
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/TrailingBlankLines:
  Enabled: true

# Offense count: 13
# Cop supports --auto-correct.
Style/DeprecatedHashMethods:
  Enabled: true


# Offense count: 11
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, ProceduralMethods, FunctionalMethods, IgnoredMethods.
Style/BlockDelimiters:
  Enabled: true

# Offense count: 9
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/BracesAroundHashParameters:
  Enabled: true



# Offense count: 1
Lint/AmbiguousRegexpLiteral:
  Enabled: true

# Offense count: 67
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/StringLiterals:
  Enabled: true


# Offense count: 55
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles, EnforcedStyleForEmptyBraces, SpaceBeforeBlockParameters.
Style/SpaceInsideBlockBraces:
  Enabled: true

# Offense count: 5
# Cop supports --auto-correct.
Style/SpaceInsideBrackets:
  Enabled: true

# Offense count: 62
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, EnforcedStyleForEmptyBraces, SupportedStyles.
Style/SpaceInsideHashLiteralBraces:
  Enabled: true


# Offense count: 1
Lint/AmbiguousOperator:
  Enabled: true


# Offense count: 18
Lint/UselessAssignment:
  Enabled: true


# Offense count: 23
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/ClassCheck:
  Enabled: true

# Offense count: 29
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/AlignParameters:
  Enabled: true

# Offense count: 96
# Cop supports --auto-correct.
Style/EmptyLines:
  Enabled: true

# Offense count: 8
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyLinesAroundBlockBody:
  Enabled: true

# Offense count: 43
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyLinesAroundClassBody:
  Enabled: true

# Offense count: 21
# Cop supports --auto-correct.
Style/EmptyLinesAroundMethodBody:
  Enabled: true

# Offense count: 60
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/EmptyLinesAroundModuleBody:
  Enabled: true

# Offense count: 1
Lint/ConditionPosition:
  Enabled: true


# ==== IDIOTIC ====

# Offense count: 18
# Cop supports --auto-correct.
# Configuration parameters: AlignWith, SupportedStyles, AutoCorrect.
Lint/EndAlignment:
  Enabled: false


# This one is idiotic because it wants the following code:


  # row_content = if replace_row_output
  #   no_rightmost_column = true
  #   replace_row_output
  # else
  #   row_content, tmp_cell_value_of_the_ordered_column = get_row_content(rendering,ar,sorting_dependant_row_cycling)
  #   cell_value_of_the_ordered_column = tmp_cell_value_of_the_ordered_column if tmp_cell_value_of_the_ordered_column
  #   row_content
  #               end

# same case:

# Offense count: 21
# Cop supports --auto-correct.
Style/ElseAlignment:
  Enabled: false

# Because it is not really a nested method definition
# Offense count: 2
Lint/NestedMethodDefinition:
  Enabled: false

# Sometimes it is important to stress that this method is an instance method
# Offense count: 30
# Cop supports --auto-correct.
Style/RedundantSelf:
  Enabled: false

# Offense count: 8
# Configuration parameters: NamePrefix, NamePrefixBlacklist.
Style/PredicateName:
  Enabled: false

# Offense count: 4
# Cop supports --auto-correct.
Style/ParallelAssignment:
  Enabled: false

# Offense count: 3
# Configuration parameters: Methods.
Style/SingleLineBlockParams:
  Enabled: false

# ==== TO DO ====

# Offense count: 7
Style/ClassVars:
  Enabled: false

# Offense count: 40
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/RaiseArgs:
  Enabled: false

# Offense count: 1
Style/RescueModifier:
  Enabled: false

# ==== I DON'T CARE ====

# Offense count: 2
Lint/Eval:
  Enabled: false


# Offense count: 559
# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 209

# Offense count: 49
Metrics/AbcSize:
  Max: 259

# Offense count: 58
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 233

# Offense count: 18
Metrics/CyclomaticComplexity:
  Max: 53


# Offense count: 19
Metrics/PerceivedComplexity:
  Max: 69

# Offense count: 8
# Configuration parameters: AllowSafeAssignment.
Lint/AssignmentInCondition:
  Enabled: false

# Offense count: 4
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Max: 421

# Offense count: 17
# Cop supports --auto-correct.
Style/ClosingParenthesisIndentation:
  Enabled: false

# Offense count: 5
Metrics/BlockNesting:
  Max: 4

# Offense count: 4
# Configuration parameters: CountKeywordArgs.
Metrics/ParameterLists:
  Max: 8

# Offense count: 11
Style/Documentation:
  Enabled: false

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/ModuleLength:
  Max: 503

# Offense count: 1
Style/AccessorMethodName:
  Enabled: false

# Offense count: 18
# Cop supports --auto-correct.
# Configuration parameters: Width.
Style/IndentationWidth:
  Enabled: false

# Offense count: 7
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Enabled: false

# Offense count: 5
# Cop supports --auto-correct.
# Configuration parameters: MaxLineLength.
Style/IfUnlessModifier:
  Enabled: false

# Offense count: 4
Style/MultilineBlockChain:
  Enabled: false


# Offense count: 2
# Cop supports --auto-correct.
# Configuration parameters: IndentWhenRelativeTo, SupportedStyles, IndentOneStep.
Style/CaseIndentation:
  Enabled: false

# Offense count: 2
# Configuration parameters: EnforcedStyle, MinBodyLength, SupportedStyles.
Style/Next:
  Enabled: false

# Offense count: 2
# Cop supports --auto-correct.
Style/TrailingUnderscoreVariable:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
Style/SpaceAfterMethodName:
  Enabled: false

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/IndentHash:
  Enabled: false


# Offense count: 1
Style/CaseEquality:
  Enabled: false




