  basics2
  upper_pagination_panel
  basics3
  basics4
  basics5
  basics6
  joining_tables
  two_associations
  many_grids_on_page
  custom_ordering
  custom_ordering2
  custom_filters1
  custom_filters2
  custom_filters3
  custom_filters4
  null_values
  buttons
  styling
  adding_rows
  no_records
  erb_mode
  integration_with_forms
  auto_reloads
  dates
  all_records
  csv_export
  detached_filters
  integration_with_application_view
  integration_with_application
  localization
  action_column
