development:
  adapter: mysql2
  encoding: utf8
  database: wice_grid_testbed_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: wice_grid_testbed_test
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  database: wice_grid_testbed_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock
