mysql: &mysql
  adapter: mysql2
  username: root
  password:
  database: <%= ENV['DB_NAME'] %>

postgresql: &postgresql
  adapter: postgresql
  username: postgres
  password:
  database: <%= ENV['DB_NAME'] %>
  min_messages: ERROR

defaults: &defaults
  pool: 5
  timeout: 5000
  host: localhost
  <<: *<%= ENV['DB'] || "postgresql" %>

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
